### ISSUE TITLE
Time Zone using getTimezoneOffset()

### ISSUE THREAD

**Issue by Asim187** [batoulapps/adhan-js#10]
Hello
Can't we use getTimezoneOffset() function instead of defining it manually?
I think it will be much useful when it is used on GPS based development.

Thanks.

**Comment by z3bi** [comment]
You can use that. Just be aware that `getTimezoneOffset()` is the offset for the user's browser. If they are getting prayer times for a different location then that could potentially be incorrect.

For making timezone based formatting better, please consider using https://momentjs.com or https://moment.github.io/luxon/

**Comment by ragaeeb** [comment]
👋 As salamu 'alaykum!

Just wondering, is it also not possible to skip `momentjs` and just use:
```
  const time = date.toLocaleTimeString('en-US', {
    timeZone,
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });
```

Where you can format it according to the timezone specified? This would get around having to import a possibly heavy module like momentjs. It will also take care of DST issues.

**Comment by z3bi** [comment]
@ragaeeb Yeah that does look it could work as well, you might just want to make sure that the browser support covers all your users.
