### ISSUE TITLE
Export sunsetTime in prayerTimes

### ISSUE THREAD

**Issue by jd1378** [batoulapps/adhan-js#105]
Hi
It would be good if the sunset time was also exported from [prayerTimes ](https://github.com/batoulapps/adhan-js/blob/master/src/PrayerTimes.js) and in the [nextPrayer ](https://github.com/batoulapps/adhan-js/blob/e2465bb88f203ce7c98a0fc777181d1698d37a8a/src/PrayerTimes.js#L185) method

because in some calculation Maqrib prayer time is not same as sunset

**Comment by z3bi** [comment]
@jd1378 is your use case that you want to be able to display both Maghrib and sunset?

**Comment by jd1378** [comment]
yes

**Comment by z3bi** [comment]
I don't think it makes sense to add it to `nextPrayer` since sunset isn't  a prayer. Maghrib is the prayer time. We include `sunrise` since thats when the prayer time for Fajr specifically ends. It might make more sense to export `SolarTime` instead if you just want times of the sunset itself.

**Comment by jd1378** [comment]
well its same usecase for maqrib in some places, it ends the prayer time for asr

**Comment by jd1378** [comment]
But exporting SolarTime would be nice as well, but that would need exporting `PolarCircleResolution` ,`TimeComponents` and `DateUtils` to do the same thing as the lib is doing

**Comment by jd1378** [comment]
I've already written a helper for myself, but I thought it would be nicer if the lib did it in the first place:
```js
import {Coordinates, PolarCircleResolution} from 'adhan';

// @ts-ignore
import {isValidDate} from 'adhan/src/DateUtils';
// @ts-ignore
import {polarCircleResolvedValues} from 'adhan/src/PolarCircleResolution';
// @ts-ignore
import SolarTime from 'adhan/src/SolarTime';
// @ts-ignore
import TimeComponents from 'adhan/src/TimeComponents';

export function getSunset(
  date: Date,
  coordinates: Coordinates,
  polarCircleResolver = PolarCircleResolution.Unresolved,
): Date {
  let solarTime = new SolarTime(date, coordinates);
  let sunsetTime = new TimeComponents(solarTime.sunset).utcDate(
    date.getFullYear(),
    date.getMonth(),
    date.getDate(),
  );
  if (
    !isValidDate(sunsetTime) &&
    polarCircleResolver !== PolarCircleResolution.Unresolved
  ) {
    const resolved = polarCircleResolvedValues(
      polarCircleResolver,
      date,
      coordinates,
    );
    solarTime = resolved.solarTime;
    const dateComponents = [
      date.getFullYear(),
      date.getMonth(),
      date.getDate(),
    ];
    sunsetTime = new TimeComponents(solarTime.sunset).utcDate(
      ...dateComponents,
    );
  }

  return sunsetTime;
}

```
