### ISSUE TITLE
Not working in older browsers - possible to transpile down to es5?

### ISSUE THREAD

**Issue by Noitidart** [batoulapps/adhan-js#123]
Our TV at the masjid is older and we use this for the clock to show times. However after upgrading to v4 we get this error:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/6372489/183964955-b07f8581-df66-4900-94e5-361267e441a1.png">

Is it possible to transpile our bundle down to es5?

**Comment by sgtsquiggs** [comment]
You're importing from `adhan/lib/esm` instead you can import from `adhan/lib/cjs` - also if you're importing adhan into a project, your project should be transpiling for you

**Comment by Noitidart** [comment]
@sgtsquiggs jzkhair for the reply! I think node_modules are excluded by default. I tried the cjs thing but its not working either. I searched cjs and it also seems to use the spread operator:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/6372489/184008572-c5390b07-0ced-4a2e-aeca-b7df6ef88e74.png">

**Comment by sgtsquiggs** [comment]
You should be able to use babel to transpile your bundled code to es5. What is your current setup?

**Comment by Noitidart** [comment]
Jzkhair for asking! I use Next.js out of the box config - its like create-react-app - https://nextjs.org/docs/getting-started just have to do `npx create-next-app@latest --typescript`

**Comment by sgtsquiggs** [comment]
Can you try adding a `.babelrc` file to the root of your project? Try this:
```
{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": {}
      }
    ]
  ],
  "plugins": []
}
```

**Comment by Noitidart** [comment]
Jzkhair so much for trying to help me when it's out of scope. Next.js already has babel. I see it also has a place to modify the webpack config too. I think maybe I can do something there to make it not exclude adhan lib from the transpilations - https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config
