### ISSUE TITLE
[suggestion]: Add 'Imsak' Timings

### ISSUE THREAD

**Issue by AyahBot-Dev** [batoulapps/adhan-js#137]

**Comment by sooluh** [comment]
Looks like Imsak was taken 10 minutes before Fajr time?

**Comment by AyahBot-Dev** [comment]
Thank you for reminding me on this. Also, maybe we need to add imsak to adjustments.

**Comment by AyahBot-Dev** [comment]
@sgtsquiggs Sorry for pinging, needed to ask if this can be on adhan-js roadmap

**Comment by sgtsquiggs** [comment]
Hi,

This isn't something we add to our adhan libraries - since Ismak is not a unique calculation and just an offset from Fajr, we expect app/site developers to implement this themselves.
