### ISSUE TITLE
add adjustment settings to sunset

### ISSUE THREAD

**Issue by meypod** [batoulapps/adhan-js#152]
Hi
currently its not possible to adjust sunset time
some of my app's users need to adjust all of the times by around 1 hour because of the DST problems

can we have this option like we have for other times ?

**Comment by z3bi** [comment]
I'm not sure what you mean, the adjustment parameter has a value for sunrise.

```
  adjustments = {
    fajr: 0,
    sunrise: 0,
    dhuhr: 0,
    asr: 0,
    maghrib: 0,
    isha: 0,
  };
```

**Comment by z3bi** [comment]
You want to adjust sunset separately from Maghrib? We don't return a sunset time, just a Maghrib time. Can you explain what is the issue you're trying to solve?

**Comment by meypod** [comment]
and I think I have explained why I need to adjust it, and it's the only remaining time that I cannot adjust

**Comment by z3bi** [comment]
You're right we do return a sunset time. However this was done as a convenience in case you needed to access it and is not part of the standard prayers we return. I am hesitant to include support in other things like being part of adjustments.

**Comment by meypod** [comment]
I don't see why not given it needs only 2-4 lines of code to support like the other times it support

And there's no pressure to do so, I can patch my packages locally to do what I need them to do
But I thought since the other times are there, it would be nice for this one to have as well (i have found a need, some one else may do as well)

**Comment by meypod** [comment]
maybe add it but also add a jsdoc to the sunset time and mention that while It's available It's not what people should normally be using ? if that's what you mean
