### ISSUE TITLE
Calculation is returning prayer times for next day instead of "today"

### ISSUE THREAD

**Issue by xsorifc28** [batoulapps/adhan-js#159]
I am trying to calculate prayer times for Chatham Islands, New Zealand (testing some extreme cases)

Input date is January 6, 2024 - `2024-01-06T00:00:00.000Z`.

Here is the output:

```js
{
   "coordinates":{
      "latitude":-43.81498724905606,
      "longitude":-176.70889987599134
   },
   "date":"2024-01-06T00:00:00.000Z",
   "calculationParameters":{
      "madhab":"shafi",
      "highLatitudeRule":"middleofthenight",
      "adjustments":{
         "fajr":0,
         "sunrise":0,
         "dhuhr":0,
         "asr":0,
         "maghrib":0,
         "isha":0
      },
      "methodAdjustments":{
         "fajr":0,
         "sunrise":-7,
         "dhuhr":5,
         "asr":4,
         "maghrib":7,
         "isha":0
      },
      "polarCircleResolution":"Unresolved",
      "rounding":"nearest",
      "shafaq":"general",
      "method":"Turkey",
      "fajrAngle":18,
      "ishaAngle":17,
      "ishaInterval":0,
      "maghribAngle":0
   },
   "fajr":"2024-01-06T13:55:00.000Z",
   "sunrise":"2024-01-06T16:06:00.000Z",
   "dhuhr":"2024-01-06T23:58:00.000Z",
   "asr":"2024-01-07T04:02:00.000Z",
   "sunset":"2024-01-07T07:32:00.000Z",
   "maghrib":"2024-01-07T07:39:00.000Z",
   "isha":"2024-01-07T09:39:00.000Z"
}
```

When converting the prayer times to the local (CHADT) time zones, the results show that the prayer times are for January 7, 2024.
```
    Fajr:     01/07/2024, 03:40 GMT+13:45
    Sunrirse: 01/07/2024, 05:51 GMT+13:45
    Dhuhr:    01/07/2024, 13:43 GMT+13:45
    Asr:      01/07/2024, 17:47 GMT+13:45
    Sunset:   01/07/2024, 21:17 GMT+13:45
    Maghrib:  01/07/2024, 21:24 GMT+13:45
    Isha:     01/07/2024, 23:24 GMT+13:45
```

I can't tell whether the times were calculated for January 6, but the time zone conversion is shifting by one day, or, if the times were calculated for January 7.

Am I misunderstanding or is there an issue with the calculation?

**Comment by xsorifc28** [comment]
Reopen?

**Comment by z3bi** [comment]
Sorry this issue has been open so long. After further investigation I believe I need to check when the solarTime computed for sunset is greater than 24 hours and apply the calculated time to date - 1.

**Comment by z3bi** [comment]
Actually after additional checking of prayer times for both Auckland and Honolulu they have the correct date applied after applying the time zone. Can you please double check your coordinates and time zone and confirm that they are both correct?

**Comment by xsorifc28** [comment]
```json
   "coordinates": {
      "latitude": -43.81498724905606,
      "longitude": -176.70889987599134
   },
   ```
   
These coordinates are for "Port Hutt Wharf" in Chatham Island. I guess because they are considered in New Zealand, they use +13:45 UTC timezone offset.
 
 Which shouldn't be a possible combination is what you are saying?

**Comment by z3bi** [comment]
Correct, a negative longitude indicates that it's west of London and east of the international date line, but a positive timezone indicates that it's east of London and west of the international date line. These two things are contradicting and create the confusion. My only recommendation would be to manually subtract a day from the resulting prayer times for this specific location.
