### ISSUE TITLE
Wrong times 

### ISSUE THREAD

**Issue by iamAdamGoodman** [batoulapps/adhan-js#162]
Prayer times are way wrong 
i tried even using different methods but no luck .

for example fajr should be around 02:37 , but it returns  00:59
the same problem with Isha time..
Im using JS

**Comment by z3bi** [comment]
@iamAdamGoodman please include the code you're using to generate the prayer times, including coordinates, and all of the settings

**Comment by ahmediriban** [comment]
Same with me.

`import { Coordinates, CalculationMethod, PrayerTimes, SunnahTimes } from 'adhan';

const coordinates = new Coordinates(41.002697, 39.716763); // Trabzon coordinates
const params = CalculationMethod.MoonsightingCommittee();
const date = new Date(2022, 3, 20);
const prayerTimes = new PrayerTimes(coordinates, date, params);`

The Fajer must be at 03:28 am but it shows at 03:59 am.

**Comment by ahmediriban** [comment]
Same with me.

```
import { Coordinates, CalculationMethod, PrayerTimes, SunnahTimes } from 'adhan';

const coordinates = new Coordinates(41.002697, 39.716763); // Trabzon coordinates
const params = CalculationMethod.MoonsightingCommittee();
const date = new Date(2022, 3, 20);
const prayerTimes = new PrayerTimes(coordinates, date, params);
```

The Fajer must be at 03:28 am but it shows at 03:59 am.

**Comment by ahmediriban** [comment]
Same with me.

```
import { Coordinates, CalculationMethod, PrayerTimes, SunnahTimes } from 'adhan';

const coordinates = new Coordinates(41.002697, 39.716763); // Trabzon coordinates
const params = CalculationMethod.MoonsightingCommittee();
const date = new Date();
const prayerTimes = new PrayerTimes(coordinates, date, params);
```

The Fajer must be at 03:28 am but it shows at 03:40 am.

PS: today is 4th August, 2024.

**Comment by z3bi** [comment]
@ahmediriban can you share the source for saying that it must be 3:28 AM? I would like to verify that the source is using the same calculation parameters as you.
