### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Dontmindmes** [batoulapps/adhan-js#2]
How would instalation be done on this? just download and put in files?

**Comment by z3bi** [comment]
@Dontmindmes yes, if you aren't using NPM then you would just download the files and put them on your server.

**Comment by Dontmindmes** [comment]
Alright, thank you i got that, btw is the location automatically grabbed?

**Comment by Dontmindmes** [comment]
Is it possible for you to implement the option to have it grab the users current location and calculate the athan time based on that like how AthanPro does it?
