### ISSUE TITLE
Shafi Asr Time Invalid

### ISSUE THREAD

**Issue by mosabdullah** [batoulapps/adhan-js#24]
I was just playing around with the library and noticed that the ASR time for Shafi Madhab does not work. 

 const coordinates = new adhan.Coordinates(153.02789306640625, -27.467580795288086);
 const params = adhan.CalculationMethod.MuslimWorldLeague();
 params.madhab = adhan.Madhab.Shafi;
 const times = new adhan.PrayerTimes(coordinates, new Date(), params);
 console.log(times);

 return as **asr: Invalid Date {}**

All other times are fine. 

The issue appears to be caused in Adhan.js in **correctedHourAngle: function**
at line 357 (**const H0 = radiansToDegrees(Math.acos(term1 / term2));**), which returns a **NaN**

Just thought you would like to know. 
<img width="1397" alt="Screen Shot 2020-07-27 at 11 39 52 pm" src="https://user-images.githubusercontent.com/195180/88548602-af060080-d062-11ea-827a-5341c2e72eb9.png">

**Comment by AbdulMalikDev** [comment]
Your params constant doesnt look right. Can you double check.

**Comment by mosabdullah** [comment]
I copied it from the example provided and changed the Madhab. The following are the params just by using the default calculation method and still the same error. I can't see what is wrong with the params?

`const params = adhan.CalculationMethod.MuslimWorldLeague();`

`adjustments: {fajr: 0, sunrise: 0, dhuhr: 0, asr: 0, maghrib: 0, …}
fajrAngle: 18
highLatitudeRule: "middleofthenight"
ishaAngle: 17
ishaInterval: 0
madhab: "shafi"
maghribAngle: undefined
method: "MuslimWorldLeague"
methodAdjustments: {dhuhr: 1}`

**Comment by z3bi** [comment]
Salam Alaikum,

I just merged in a fix #23 where the TypeScript definition for the Coordinate object had the parameter names switched by mistake. It looks like for your coordinates they need to be flipped. That is what is causing the issue.

**Comment by mosabdullah** [comment]
Wa Alaykum Isalaam. 

Jazakum ullahu Kahiran for that. I just went by what the IDE showed the parameters as. I will test it and close this if it is fixed, Inshallah.

**Comment by mosabdullah** [comment]
The fix worked. Thanks.
