### ISSUE TITLE
How to Display both Shafii and Hanafi Asr? Also, Hanafi Eishaa?

### ISSUE THREAD

**Issue by natesct** [batoulapps/adhan-js#32]

**Comment by natesct** [comment]
Asr (Hanafi) - time
Asr (Shafi) - time

Isha(Hanafi) - time
Isha (Shafi) - time

**Comment by z3bi** [comment]
@natesct there is a config option for madhab to set whether Asr will be calculated according to the Hanafi or Shafi time. This is explained here https://github.com/batoulapps/adhan-js#initialization-parameters

If you want to show both times you would need to compute the prayer times twice and change the madhab for each one.

The library doesn't have a differentiation between Hanafi and Shafi for Isha time.

**Comment by natesct** [comment]
Shukran for your response...

1. Yeah I did that for Hanafi/Shafii, I was just curious if there was a way withou doing that
2.  iA that gets added at some stage
