### ISSUE TITLE
About Sunset Time

### ISSUE THREAD

**Issue by MS-Jahan** [batoulapps/adhan-js#33]
How to get sunset time?

**Comment by z3bi** [comment]
The library really only provides an interface for Maghrib prayer which based on the calculation method can be slightly after sunset. However you could calculate prayer times using the method of other `adhan.CalculationMethod.Other()` and then maghrib time will be equivalent to sunset time.

**Comment by MS-Jahan** [comment]
Okay, I was wanting to show end time for Asr prayer. Generally, Asr time is ended at the sunset time, then some time for sunset and then the Maghrib starts.

**Comment by z3bi** [comment]
@MS-Jahan it's a good general rule that the end time for Asr should be about 10 minutes before Maghrib time.

**Comment by MS-Jahan** [comment]
> @MS-Jahan it's a good general rule that the end time for Asr should be about 10 minutes before Maghrib time.

Thank you so much. Closing this issue.
