### ISSUE TITLE
"Upcoming: None at 02:00"

### ISSUE THREAD

**Issue by natesct** [batoulapps/adhan-js#34]
not sure if I am the only one getting this one "next prayer". If the time has passed Isha, it shows this "None at 02:00"

**Comment by z3bi** [comment]
This is actually the intended behavior. Getting "None" back is the indication for the developer to then calculate prayer times for the next day and then use that.

**Comment by natesct** [comment]
Thanks for that.

If I get midnight and last 1/3 which can be after or before, then does that apply to the day before 00:00 or after 00:00

**Comment by z3bi** [comment]
@natesct they will apply to the day after the date you provided to the function.

**Comment by natesct** [comment]
thanks very much
