### ISSUE TITLE
difference between adjustments and methodAdjustments

### ISSUE THREAD

**Issue by gimyboya** [batoulapps/adhan-js#36]
What's the difference between `adjustments` and `methodAdjustments` in the params?

**Comment by sgtsquiggs** [comment]
Hi,

`methodAdjustments` are internal adjustments required for the selected calculation method
`adjustments` are exterrnal manual adjustments made by you

**Comment by gimyboya** [comment]
Thank you for the reply @sgtsquiggs.
So if I understand correctly if we have `params.methodAdjustment.dhuhr = 1` and then `params.adjustmens.dhuhr = 1` that would make dhuhr adjust by 2?

**Comment by sgtsquiggs** [comment]
@gimyboya yes! the reasoning is that certain calc methods require an offset from the mathematical result. having the separate `adjustments` var allows the developer to separate calculation-based offsets from user-defined offsets.

**Comment by gimyboya** [comment]
Perfect! I just found the line of code responsible for it [here](https://github.com/batoulapps/adhan-js/blob/c0a721ae53d77bdf0648c383a5a349f077eae770/src/PrayerTimes.js#L120).

Thank you for the explanation I appreciate it.
