### ISSUE TITLE
Release latest progress

### ISSUE THREAD

**Issue by gimyboya** [batoulapps/adhan-js#37]
Assalam alykoum

It seems to me that the current version `4.0.1` is behind `master` branch. for example, the type definitions in the latest release don't include `polarCircleResolution`. and I noticed that the Quibla feature is not defined in the current type definitions (probably needs a separate issue. let me know and I will open a new one).

How are the releases triggered?

**Comment by z3bi** [comment]
They are released manually, it looks like we forgot to issue a new release after that last merge. We will go ahead and get that in inshAllah.

**Comment by z3bi** [comment]
Perhaps it would be best to wait for the fixes to the typescript definition you mentioned and then we will release a new version.

**Comment by gimyboya** [comment]
@z3bi may I suggest that we use [`sementic-release`](https://github.com/semantic-release/semantic-release) for this project to release a new version every time we push to master? If you guys are interested to see something like that I can create a pr for it as well.

**Comment by z3bi** [comment]
@gimyboya thats not a bad idea, it might also be a good time to adopt commit conventions.

**Comment by gimyboya** [comment]
@z3bi any progress with this issue ?

**Comment by z3bi** [comment]
@gimyboya sorry I haven't responded to the PR yet, its a fairly large PR and the past week has been a bit busy for me. Will try to take a good look at it this weekend.

**Comment by gimyboya** [comment]
Alright, no worries. if you have any questions please let me know
