### ISSUE TITLE
Could the time ismak be added?

### ISSUE THREAD

**Issue by natashajaved** [batoulapps/adhan-js#48]
In my project I need to add Imsak time as well. could this feature be added?

**Comment by ameirwillowtree** [comment]
"imsak" is not a calculated time, instead you just take the time for fajr and subtract 10 minutes. Imsak time is only used as a precaution during ramadan to ensure that eating of suhoor stops the time for Fajr enters.

**Comment by Noitidart** [comment]
Thanks for asking and explaining ismak. I was having this question.
