### ISSUE TITLE
Add type definitions for TypeScript

### ISSUE THREAD

**Issue by arafatamim** [batoulapps/adhan-js#6]
Are there any plans to add type definitions for TypeScript users?
This would be a huge benefit for us. JavaScript programmers that use VSCode would also benefit from better completions.

**Comment by z3bi** [comment]
That sounds like a good idea, is this something you would be interested in assisting with? I am not completely up-to-date on TypeScript.

**Comment by arafatamim** [comment]
I would very much like to. Maybe I'll have a go at it once I am much more familiarised with creating type definitions.

**Comment by skymunn** [comment]
Actually, i make some commit to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39932) for this Module. But, sadly after commit, all check has failed. Hope that crew will fix the commit.

**Comment by skymunn** [comment]
I just make some typings in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39942) for this project.

I make this typings because I'm not confusing to using your library in my project because my project using React Native. I hope you like it.

**Comment by skymunn** [comment]
Good news! My typings has merged into DefinitelyTyped, you can check it in this link.
https://www.npmjs.com/package/@types/adhan

**Comment by z3bi** [comment]
TypeScript definitions are now included directly in the package. I would recommend using these as they will be kept in sync with any changes to the interface.
