### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by farisfaisalthena** [batoulapps/adhan-js#63]
I have two suggestion. One is instead if including the normal date maybe also provide the Hijri calendar. Secondly is to add the time for next prayer. Currently when using the next prayers function it only provides the type of prayers which is like 'asr' instead you could do something like `{ name: asr, time: 1:04PM }`

**Comment by z3bi** [comment]
there is a `timeForPrayer` function where you can pass in any prayer you want, including the result of the `nextPrayer` function.

**Comment by farisfaisalthena** [comment]
Oh yeah sorry i got it.. then it would be great to have Hijri calendar and normal calendar for prayers time
