### ISSUE TITLE
How to display prayer times of one month or later

### ISSUE THREAD

**Issue by Asim187** [batoulapps/adhan-js#9]
First of All, Thanks for Great Script may Allah give you best return for your work

If I want to display prayer times of one month can it be possible with this script?
If yes then what will be the method.

**Comment by z3bi** [comment]
Yes that is certainly possible. It will be up to you to create a Date object for each day of the month, and then you can pass each of those date objects create a new PrayerTimes object.

something like this:

```
const monthDays = [Date(...), Date(...), etc];

monthDays(function(day){
   const times = new adhan.PrayerTimes(coordinates, day, params)
})
```

**Comment by Asim187** [comment]
it will be more helpful if you give an example

**Comment by z3bi** [comment]
@Asim187 yes, if you use moment.js you an do something like:
```
moment(prayerTimes.fajr).tz('America/New_York').format('HH:mm');
```
